FROM nginx:1.27-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY SuperBizAgentFrontend/index.html /usr/share/nginx/html/
COPY SuperBizAgentFrontend/app.js     /usr/share/nginx/html/
COPY SuperBizAgentFrontend/styles.css /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
